version: "3"

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"